platform :ios, '7.0' 
pod 'AMap2DMap' 
pod 'AMapSearch' 
pod 'AVOSCloud'
pod 'AVOSCloudIM'
pod "AFNetworking", "~> 2.0"
pod 'XXNibBridge', '~> 2.2'
pod 'SDWebImage', '~>3.7'
pod 'MBProgressHUD', '~> 0.9.1'